// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlXSx4u21A4aYjz5wztdjDgbkTSKJbno',
    appId: '1:373551582295:web:37da48db67ac7de941a712',
    messagingSenderId: '373551582295',
    projectId: 'milo-locator',
    authDomain: 'milo-locator.firebaseapp.com',
    storageBucket: 'milo-locator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwz9YuAeA--zvf4WR_MoRoE_X5W0zqF9E',
    appId: '1:373551582295:android:5e3822dcba402c3241a712',
    messagingSenderId: '373551582295',
    projectId: 'milo-locator',
    storageBucket: 'milo-locator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmtSVc7b9EnGbYgkZqesJpzM-b_EfkbR4',
    appId: '1:373551582295:ios:f972e645e5164f1441a712',
    messagingSenderId: '373551582295',
    projectId: 'milo-locator',
    storageBucket: 'milo-locator.appspot.com',
    iosClientId: '373551582295-bs4rnu108e675f7tjbjhjm7lpgld2s51.apps.googleusercontent.com',
    iosBundleId: 'com.levels.miloLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmtSVc7b9EnGbYgkZqesJpzM-b_EfkbR4',
    appId: '1:373551582295:ios:f972e645e5164f1441a712',
    messagingSenderId: '373551582295',
    projectId: 'milo-locator',
    storageBucket: 'milo-locator.appspot.com',
    iosClientId: '373551582295-bs4rnu108e675f7tjbjhjm7lpgld2s51.apps.googleusercontent.com',
    iosBundleId: 'com.levels.miloLocator',
  );
}
